address/urls.py
from django.urls import path

from . import views

app_name = 'address'

urlpatterns = [
	path("", views.address_list, name="addresses"),
	path("session-update", views.address_session_view, name="address-session-update"),
	path("add/", views.add_address, name="add_address"),
	path("edit/<uuid:id>", views.edit_address, name="edit_address"),
	path("delete/<uuid:id>", views.delete_address, name="delete_address"),
	path("set_default/<uuid:id>", views.default_address, name="set_default"),
]

checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'

urlpatterns = [
	path('', views.CheckoutView, name='checkout'),
	path('update-delivery-charges', views.UpdateDeliveryChargesInBasket, name='update-dc-in-basket')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("account/", include("account.urls", namespace="account")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("more/", include("more.urls", namespace="more")),
    path("order/", include("order.urls", namespace="order")),
    path("address/", include("address.urls", namespace="address")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("__reload__/", include("django_browser_reload.urls")),
]

# add at the last
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
	path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
	path('order_placement/', views.Order_placement, name='order-placement'),
	# orders history
	path('orders-history/', views.orders_history, name="orders-history"),
	# order cancel
	path('cancel-order/', views.order_cancel, name='order-cancel'),
	# order item cancel/remove
	path('order-item-remove/', views.order_item_remove, name='order-item-remove'),
]

checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class DeliveryOptions(models.Model):
	"""
	The Delivery methods table containing all delivery
	"""

	delivery_name = models.CharField(help_text=_('Required - e.g., Standard Delivery or Express Delivery e.t.c.'), max_length=255)
	within_city_dc = models.DecimalField(verbose_name=_("Within City Delivery Charges"), max_digits=5, decimal_places=2, help_text=_("Price must be between 0 and 999.99"))
	other_city_dc = models.DecimalField(verbose_name=_("Other Cities Delivery Charges"), max_digits=5, decimal_places=2, help_text=_("Price must be between 0 and 999.99"))
	delivery_timeframe = models.CharField(verbose_name=_("Delivery Time-Frame"), help_text=_("Required - e.g., '3-4 days'"), max_length=255)
	delivery_window = models.CharField(verbose_name=_("Delivery Window"), help_text=_("Required - e.g., '9:00am - 5:00pm'"), max_length=255)
	order = models.IntegerField(verbose_name=_("Delivery Option Order Number"), help_text=_("Required - Order number of which it should be displayed in delivery option list on checkout page"), default=0)
	is_active = models.BooleanField(default=True)

	class Meta:
		verbose_name = ("Delivery Option")
		verbose_name_plural = ("Delivery Options")
		ordering = (('order'),)
	
	def __str__(self):
		return self.delivery_name

more/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import EmailValidator


class NewsLetter(models.Model):
	email = models.EmailField(unique=True, validators=[EmailValidator()])
	subscribed = models.BooleanField(default=True)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	class Meta:
			verbose_name = 'Newsletter Subscription'
			verbose_name_plural = 'Newsletter Subscriptions'
			ordering = ['-created_at']

	def __str__(self):
		return f"{self.email} ({'Active' if self.active else 'Inactive'})"

order/models.py
import uuid
from django.conf import settings
from django_countries.fields import CountryField
from django.db import models
from django.utils import timezone

from store.models import Product, ProductSpecificationValue

# Create your models here.


class Order(models.Model):
	ORDER_STATUS_CHOICES = (
		("F", "Fullfilled"),
		("P", "In Process"),
		("C", "Is Cancelled"),
	)
	DELIVERY_STATUS_CHOICES = (
		("D", "Delivered"),
		("P", "In Process"),
		("C", "Is Cancelled"),
	)

	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

	user = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		related_name="order",
		blank=True,
		null=True,
	)
	items = models.ManyToManyField("store.Product", through='OrderItem')

	# payment
	total_payment = models.DecimalField(max_digits=10, decimal_places=2)
	paid = models.BooleanField(default=False)
	PAYMENT_CHOICES = (("COD", "Cash on Delivery"),)
	payment = models.CharField(max_length=15, choices=PAYMENT_CHOICES, default="COD")

	# order
	order_created = models.DateTimeField(auto_now_add=True)
	order_updated = models.DateTimeField(auto_now=True)
	order_status = models.CharField(
		max_length=2, choices=ORDER_STATUS_CHOICES, default="P"
	)

	# cancel
	is_cancelled = models.BooleanField(default=False)

	# delivery
	delivery_status = models.CharField(
		max_length=2, choices=DELIVERY_STATUS_CHOICES, default="P"
	)
	delivered_date = models.DateTimeField(blank=True, null=True)
	delivered = models.BooleanField(default=False)

	# billing address details
	# required
	first_name = models.CharField(max_length=25)
	last_name = models.CharField(max_length=25)
	email = models.EmailField()
	# optional, that if billing address exits then no need to reenter data into these fields
	phone_number = models.CharField(max_length=15, blank=True, null=True)
	address_line_1 = models.CharField(max_length=150, blank=True, null=True)
	address_line_2 = models.CharField(max_length=150, blank=True, null=True)
	city = models.CharField(max_length=150, blank=True, null=True)
	state = models.CharField(max_length=150, blank=True, null=True)
	country = CountryField(blank_label="Country", blank=True, null=True)
	zip_code = models.CharField(max_length=12, blank=True, null=True)

	class Meta:
		ordering = ("-order_created",)
	
	def __str__(self):
		if self.user:
			f_name = self.user.first_name
			l_name = self.user.last_name
		else:
			f_name = self.first_name
			l_name = self.last_name
		order_placed = self.order_created.strftime("%I:%M %p | %d-%m-%Y")
		return f"{f_name} {l_name} | {order_placed}"

	def can_be_cancelled(self):
		return (timezone.now() - self.order_created).total_seconds() <= 12 * 60 *60



class OrderItem(models.Model):
	order = models.ForeignKey(
		Order,
		on_delete=models.CASCADE,
		related_name="order_items"
	)
	item = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
	quantity = models.IntegerField(default=1)
	is_cancelled = models.BooleanField(default=False)

	def __str__(self):
		if self.is_cancelled:
			option = 'Cancelled'
		else:
			option = ', '.join(str(attr) for attr in self.order_item_attribute.all())
		return f"{self.order.id} ----- {self.quantity} of {self.item.title} ----- {option}"


class OrderItemAttribute(models.Model):
	order_item = models.ForeignKey(OrderItem, on_delete=models.CASCADE, related_name="order_item_attribute")
	attribute = models.ForeignKey(ProductSpecificationValue, on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.attribute.specification.name}: {self.attribute.value}'

checkout/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.contrib import messages

from address.forms import BillingForm
from address.models import BillingAddress
from address.billingaddress import Billing

from .models import DeliveryOptions
from basket.basket import Basket


def CheckoutView(request):
	"""
	Order checkout to add address.
	"""
	billing_session = Billing(request)
	basket = Basket(request)
	basketqty = basket.__len__()
	if basketqty <= 0:
		messages.error(request, "Your basket is empty.")
		return redirect("store:index")

	delivery_options = DeliveryOptions.objects.filter(is_active=True)

	if request.POST:
		if request.user.is_authenticated:
			try:
				billing = BillingAddress.objects.get(
					customer=request.user, default=True
				)
				bform = BillingForm(request.POST, instance=billing)
			except ObjectDoesNotExist:
				bform = BillingForm(request.POST)

			if bform.is_valid():
				if bform.cleaned_data["save_info"]:
					billingsave = bform.save(commit=False)
					billingsave.customer = request.user
					billingsave.default = True
					billingsave.save()
				billing_session.add(bform, request.user.id)
			else:
				return render(request, "checkout/checkout.html", {"form": bform, 'delivery_options': delivery_options})
		else:
			bform = BillingForm(request.POST)
			if bform.is_valid():
				billing_session.add(bform, "Anonymous")
			else:
				return render(request, "checkout/checkout.html", {"form": bform, 'delivery_options': delivery_options})

		return HttpResponseRedirect(reverse("order:order-placement"))
	else:
		if request.user.is_authenticated:
			try:
				address = BillingAddress.objects.get(
					customer=request.user, default=True
				)
				return render(
					request, "checkout/checkout.html", {"address": address, 'delivery_options': delivery_options}
				)

			except ObjectDoesNotExist:
				bform = BillingForm(
					initial={
						"first_name": request.user.first_name,
						"last_name": request.user.last_name,
						"email": request.user.email,
					}
				)
		elif billing_session.__len__() != 0:
			billing_address = billing_session.billing_address["Anonymous"]
			bform.initial = {
				"first_name": billing_address["first_name"],
				"last_name": billing_address["last_name"],
				"email": billing_address["email"],
				"phone_number": billing_address["phone_number"],
				"address_line_1": billing_address["address_line_1"],
				"address_line_2": billing_address["address_line_2"],
				"city": billing_address["city"],
				"state": billing_address["state"],
				"country": billing_address["country"],
				"zip_code": billing_address["zip_code"],
			}
		else:
			bform = BillingForm()
		
		return render(request, "checkout/checkout.html", {"form": bform, 'delivery_options': delivery_options})


def UpdateDeliveryChargesInBasket(request):
	basket = Basket(request)

	if request.POST.get('action') == 'post':
		delivery_option_id = int(request.POST.get('delivery_option_id'))
		city = request.POST.get('city')
		delivery_option = DeliveryOptions.objects.get(id=delivery_option_id)

		if city == 'lhr':
			dc = delivery_option.within_city_dc
		else:
			dc = delivery_option.other_city_dc

		basket.add_delivery_charges(dc)
		
		response = JsonResponse({'dc': dc, 'total_price': basket.get_total_price()})
		return response

templates/checkout/checkout.html
{% extends 'store/layout.html' %}
{% load static %}

{% block title %}Checkout{% endblock %}

{% block style %}
	<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock %}

{% block body %}
<div class="container-fluid px-5">
	<div class="row no-gutter g-0">
		<div class="col-12 {% if form %}col-md-10 col-xl-4{% else %}col-md-6 col-lg-4{% endif %} order-xl-last mt-4 m-auto">
			<div class="container-fluid px-md-1">
				<div class="row row-cols-1">
					<div class="col">
						<h3 class="d-flex justify-content-between align-items-center mb-3">
							<span>Delivery Options</span>
						</h3>
						<ul class="list-group p-2 mb-3 checkout-list rounded-4 {% if not form %}shadow{% endif %}">
							{% for option in delivery_options %}
								<li class="list-group-item d-flex justify-content-between gap-2 align-items-center {% if not form %}bg-transparent{% endif %} lh-sm">
									<label class="d-flex gap-3" for="id_{{ option.id }}">
										<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-truck m-auto" viewBox="0 0 16 16">
											<path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
										</svg>
										<div class="ms-0 ps-0">
											<h6 class="my-0 ms-0 ps-0">{{ option.delivery_name }}</h6>
											<small class="text-muted">Your order should be delivered within {{ option.delivery_timeframe }} </small>
										</div>
									</label>
									<span class="text-body-secondary">
										<input type="radio" class="form-check-input" name="del_option" value="{{ option.id }}" id="id_{{ option.id }}" {% if forloop.first %} checked {% endif %}>
									</span>
								</li>
							{% endfor %}
						</ul>
					</div>
					<div class="col">
						{% with total_qty=basket|length %}
							<h3 class="d-flex justify-content-between align-items-center mb-3">
								<span>Your Cart</span>
								<span class="badge">
									<span class="basket-qty text-black d-inline-flex">{{ total_qty }}</span>
								</span>
							</h3>
							<ul class="list-group p-2 mb-3 checkout-list rounded-4 {% if not form %}shadow{% endif %}">
								{% if not total_qty == 0 %}
									{% for item in basket %}
										{% with product=item.product %}
											<li class="list-group-item d-flex justify-content-between {% if not form %}bg-transparent{% endif %} lh-sm">
												<div>
													<h6 class="my-0">{{ product.title }}</h6>
													<small class="text-body-secondary">{{ product.description | truncatechars:30 }}</small>
												</div>
												<span class="text-body-secondary">Rs. {{ item.total_price|floatformat }} ({{ item.qty }})</span>
											</li>
										{% endwith %}
									{% endfor %}
								{% endif %}
								<li class="list-group-item d-flex justify-content-between {% if not form %}bg-transparent{% endif %}">
									<span>Sub Total (PKR)</span>
									<strong>Rs. {{ basket.get_before_discount_subtotal_price|floatformat }}</strong>
								</li>
								<li class="list-group-item d-flex justify-content-between {% if not form %}bg-transparent{% endif %}">
									{% if basket.get_discount_price > 0 %}
									<div class="text-success">
										<h6 class="my-0">Discount</h6>
										<small>Special Discount for You</small>
									</div>
									<span class="text-success">-Rs. {{ basket.get_discount_price|floatformat }}</span>
									{% else %}
									<div class="text-danger">
										<h6 class="my-0">Discount</h6>
										<small>Sorry! No discount available</small>
									</div>
									<span class="text-danger">Rs. {{ basket.get_discount_price|floatformat }}</span>
									{% endif %}
								</li>
								<li class="list-group-item d-flex justify-content-between {% if not form %}bg-transparent{% endif %}">
									<div class="text-info-emphasis">
										<h6 class="my-0">Delivery Charges</h6>
									</div>
									<span class="text-info-emphasis" id="dc_value">Rs. 0</span>
								</li>
								<li class="list-group-item d-flex justify-content-between bg-body-tertiary rounded-bottom-4">
									<span>Total (PKR)</span>
									<strong id="total_price">Rs. {{ basket.get_total_price|floatformat }}</strong>
								</li>
								<li class="list-group-item border-0 d-flex justify-content-between bg-transparent">
									{% if not form %}
										<a href="{% url 'order:order-placement' %}" id="confirm_order" class="w-75 mt-2 m-auto"><button class="btn btn-primary rounded-0 fs-5 w-100" role="button" disabled><span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Loading...</button></a>
									{% endif %}
								</li>
							</ul>
						{% endwith %}
					</div>
				</div>
			</div>
		</div>
		{% if form %}
		<div class="col-12 col-md-10 col-xl-6 mx-auto">
			<div class="auth_form">
				<form action="" method="post">
					{% csrf_token %}
					<h3 class="mb-3">Billing Address</h3>

					{% if form.errors %}
					<p class="text-danger">Please correct the following errors:</p>
					{% for field in form %}
					{% if field.errors %}
					<div class="alert alert-danger alert-dismissible fade show" role="alert">
						{{ field.label }}: {{ field.errors | striptags }}
						<button type="button" class="btn-close" data-bs-dismiss="alert"
							aria-label="Close"></button>
					</div>
					{% endif %}
					{% endfor %}
					{% endif %}

					<div class="row">
						<div class="col-12 col-sm-6">
							<label for="id_first_name">{{ form.first_name.label }}</label>
							{{ form.first_name }}
						</div>
						<div class="col-12 col-sm-6">
							<label for="id_last_name">{{ form.last_name.label }}</label>
							{{ form.last_name }}
						</div>
					</div>
					<div class="row">
						<div class="col-12 col-md-6">
							<label for="id_email">{{ form.email.label }}</label>
							{{ form.email }}
						</div>
						<div class="col-12 col-md-6">
							<label for="id_phone_number">{{ form.phone_number.label }}</label>
							{{ form.phone_number }}
						</div>
					</div>
					<div class="row">
						<div class="col-12 col-md-6">
							<label for="id_address_line_1">{{ form.address_line_1.label }}</label>
							{{ form.address_line_1 }}
						</div>
						<div class="col-12 col-md-6">
							<label for="id_address_line_2">{{ form.address_line_2.label }} <span
									class="text-muted small">(Optional)</span></label>
							{{ form.address_line_2 }}
						</div>
					</div>
					<div class="row g-xxl-2">
						<div class="col-12 col-sm-6 col-xxl-3">
							<label for="id_city">{{ form.city.label }}</label>
							{{ form.city }}
						</div>
						<div class="col-12 col-sm-6 col-xxl-4">
							<label for="id_state">{{ form.state.label }}</label>
							{{ form.state }}
						</div>
						<div class="col-12 col-sm-6 col-xxl-3">
							<label for="id_country">{{ form.country.label }}</label>
							{{ form.country }}
						</div>
						<div class="col-12 col-sm-6 col-xxl-2">
							<label for="id_zip_code">{{ form.zip_code.label }}</label>
							{{ form.zip_code }}
						</div>
					</div>
					{% if user.is_authenticated %}
						<hr>
						{{ form.save_info }}
						<label for="id_save_info" style="cursor: pointer;">{{ form.save_info.label }}</label>
					{% endif %}

					<h3 class="my-3">{{ form.payment_method.label }}</h3>
					{{ form.payment_method }}

					<button class="btn btn-primary w-100 mt-4" type="submit">Confirm Order</button>
				</form>
			</div>
		</div>
		{% else %}
		<div class="col-12 col-md-5 col-md-5 me-lg-0 p-0 order-first mt-4 m-auto">
			<h3 class="mb-3">
				<span>Your Default Address</span>
			</h3>
			<ul class="list-group p-2 mb-3 checkout-list rounded-4 shadow">
				<li class="list-group-item lh-sm bg-transparent">
					<div>
						<h6 class="my-0 title">Name</h6>
						<small class="text-body-secondary">{{ address.first_name }} {{ address.last_name }}</small>
					</div>
				</li>
				<li class="list-group-item lh-sm bg-transparent">
					<div>
						<h6 class="my-0 title">Phone Number</h6>
						<small class="text-body-secondary">{{ address.phone_number }}</small>
					</div>
				</li>
				<li class="list-group-item lh-sm bg-transparent">
					<div>
						<h6 class="my-0 title">Email</h6>
						<small class="text-body-secondary">{{ address.email }}</small>
					</div>
				</li>
				<li class="list-group-item lh-sm bg-transparent">
					<div>
						<h6 class="my-0 title">Address</h6>
						<small class="text-body-secondary">{{ address.address_line_1 }}</small>
					</div>
				</li>
				{% if address.address_line_2 %}
				<li class="list-group-item lh-sm bg-transparent">
					<div>
						<h6 class="my-0 title">Address</h6>
						<small class="text-body-secondary">{{ address.address_line_2 }}</small>
					</div>
				</li>
				{% endif %}
				<li class="list-group-item lh-sm bg-transparent">
					<div>
						<h6 class="my-0 title">Area</h6>
						<small class="text-body-secondary">{{ address.get_city_display }}, {{ address.get_country_display }}</small>
					</div>
					<span class="text-body-secondary my-auto">{{ address.zip_code }}</span>
				</li>
			</ul>
			<div class="row gap-3 px-2 text-center">
				<a href="{% url 'address:addresses' %}" class="col btn btn-secondary mt-3">Change Address</a>
				<a href="{% url 'address:add_address' %}" class="col btn btn-secondary mt-3 d-flex align-items-center justify-content-center gap-2"><ion-icon name="add-outline"></ion-icon>Add New Address</a>
			</div>
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}

{% block script %}
{% if not form %}
<script>
	$(document).ready(function () {
		var csrfToken = "{{ csrf_token }}";
		$.ajax({
			type: "post",
			url: "{% url 'address:address-session-update' %}",
			data: {
				csrfmiddlewaretoken: csrfToken,
				action: 'post'
			},
			success: function (response) {
				console.log(response.message);
				$('#confirm_order > button').prop('disabled', false);
				$('#confirm_order > button').text('Confirm Order');
			},
			error: function (xhr, errmessage, err) {
				console.log('error occurred');
				console.log(err);
			}
		});

		$.ajax({
			type: 'post',
			url: "{% url 'checkout:update-dc-in-basket' %}",
			data: {
				csrfmiddlewaretoken: csrfToken,
				delivery_option_id: $('input[type="radio"][name="del_option"]').val(),
				city: '{{ address.city }}',
				action: 'post'
			},
			success: function (response) {
				$('#dc_value').text('Rs. ' + response.dc);
				$('#total_price').text('Rs. ' + response.total_price);
			},
			error: function (xhr, errmessage, err) {
				console.log('error occurred');
				console.log(err);
				console.log(errmessage);
			}
		});
	});
</script>
{% else %}
<script>
	$(document).ready(function () {
		var csrfToken = "{{ csrf_token }}";

		$('#id_city').on('change', () => {
			updateBasket();
		})

		updateBasket();
		function updateBasket() {
			$.ajax({
				type: 'post',
				url: "{% url 'checkout:update-dc-in-basket' %}",
				data: {
					csrfmiddlewaretoken: csrfToken,
					delivery_option_id: $('input[type="radio"][name="del_option"]').val(),
					city: $('#id_city').val(),
					action: 'post'
				},
				success: function (response) {
					$('#dc_value').text('Rs. ' + response.dc);
					$('#total_price').text('Rs. ' + response.total_price);
				},
				error: function (xhr, errmessage, err) {
					console.log('error occurred');
					console.log(err);
					console.log(errmessage);
				}
			});
		}
	})
</script>
{% endif %}
{% endblock %}