account/urls.py
from django.urls import path
from django.contrib.auth.views import (LoginView, PasswordResetView, PasswordResetConfirmView)
from django.views.generic import TemplateView

from . import views
from .forms import (LoginForm, PwdResetForm, PwdResetConfirmForm)

app_name = 'account'

urlpatterns = [
	# login
	path("login/", views.CustomLoginView.as_view(
		template_name='account/user/login.html', 
		form_class=LoginForm
	), name="login"),
	# logout
	path("logout/", views.logout_view, name="logout"),
	# register
	path('register/', views.register, name='register'),
	# account activation
	path('activate/<slug:uid64>/<slug:token>/', views.account_activate, name='activate'),
	# password reset
	path('password_reset/', PasswordResetView.as_view(
		template_name='account/pwd_reset/password_reset.html',
		success_url='password_reset/password_reset_email_confirm/',
		email_template_name='account/pwd_reset/password_reset_email.html',
		form_class=PwdResetForm
		), name='pwd_reset'),
	# password reset email confirm
	path('password_reset/password_reset_email_confirm/', views.CustomLoginView.as_view(
		template_name='account/user/login.html', 
		form_class=LoginForm
		), name='password_reset_done'),
	# password reset confirm
	path('password_reset_confirm/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(
		template_name='account/pwd_reset/password_reset_confirm.html',
		success_url='password_reset_complete/',
		form_class=PwdResetConfirmForm
		), name='pwd_reset_confirm'),
	# password reset complete
	path('password_reset_confirm/MTA/set-password/password_reset_complete/', views.CustomLoginView.as_view(
		template_name='account/user/login.html', 
		form_class=LoginForm
		), name='password_reset_complete'),

	# user dashboard
	path('dashboard/', views.dashboard, name='dashboard'),
	# profile update
	path('profile/edit/', views.edit_details, name='edit_details'),
	# profile delete
	path('profile/delete/user/', views.delete_user, name='delete_user'),
	# profile delete confirmation
	path('profile/delete_confirm/', TemplateView.as_view(template_name='account/user/delete_confirm.html'), name='delete_confirm'),
	# wishlist
	path('wishlist/', views.WishlistView.as_view(), name="wishlist"),
	path('wishlist/add/<slug:product_slug>/', views.add_to_wishlist_view, name="add-to-wishlist"),
]

basket/urls.py
from django.urls import path

from . import views


app_name = 'basket'

urlpatterns = [
	path('', views.basket_summary, name='basket_summary'),
	path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("account/", include("account.urls", namespace="account")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("more/", include("more.urls", namespace="more")),
    path("order/", include("order.urls", namespace="order")),
    path("address/", include("address.urls", namespace="address")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("__reload__/", include("django_browser_reload.urls")),
]

# add at the last
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

more/urls.py
from django.urls import path

from . import views

app_name = 'more'

urlpatterns = [
	# Subscription
	path('subscribe/', views.subscribe_view, name="subscribe"),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
	# Home Url
	path('', views.HomeView.as_view(), name='index'),

	# Catalog Url
	path('catalog/', views.CatalogView.as_view(), name='catalog'),
	path('catalog/<str:category_title>/', views.CatalogView.as_view(), name='catalog_category'),
	# Category Url
	path('category/<uuid:category_id>/', views.CategoryListView.as_view(), name='products-by-category'),
	# Features Url
	path('collection/<slug:collection_slug>/', views.CollectionListView.as_view(), name='products-by-collection'),
	# Discount Url
	path('discount/', views.DiscountListView.as_view(), name='discount-products'),

	# Product Detail Url
	path('product/<slug>/', views.ProductDetailView.as_view(), name='product'),

	# About Us Url
	path('about-us/', views.AboutView.as_view(), name='about-us'),
	# Contact Us API Url
	path('contact/', views.contact_view, name='contact-us')
]

store/forms.py
from django import forms

# Custom Multile File Input Class
class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


# Custom Multile File Field Class
class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class ContactForm(forms.Form):
	fname = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First Name', 'class': 'form-control'}))
	lname = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'form-control'}), required=False)
	email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
	message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Message', 'class': 'form-control', 'rows': 4}))

store/views.py
import logging
import json

from django.http import JsonResponse, Http404
from django.db.models import Exists, OuterRef
from django.core.mail import send_mail
from django.views.generic import DetailView, ListView, TemplateView
from django.views.decorators.csrf import csrf_protect

from store.decorators import rate_limit
from store.forms import ContactForm

from .models import Product, Category, Collection


logger = logging.getLogger(__name__)


class HomeView(TemplateView):
    template_name = 'store/index.html'


class AboutView(TemplateView):
    template_name = 'store/about_us.html'


class CatalogView(ListView):
	model = Product
	paginate_by = 12
	template_name = 'store/list.html'

	def get_queryset(self, **kwargs):
		category_title = self.kwargs.get('category_title')

		if not category_title:
			if self.request.user.is_authenticated:
				return Product.products.all().annotate(
					is_wishlisted=Exists(
						Product.objects.filter(
							id=OuterRef('id'),
							wishlist=self.request.user
						)
					)
				)
			return Product.products.all()

		try:
			category = Category.objects.get(title__iexact=category_title.replace("-", " ").title())
			if self.request.user.is_authenticated:
				return Product.products.filter(category__in=category.get_descendants(include_self=True)).annotate(
					is_wishlisted=Exists(
						Product.objects.filter(
							id=OuterRef('id'),
							wishlist=self.request.user
						)
					)
				)
			return Product.products.filter(category__in=category.get_descendants(include_self=True))
		except Category.DoesNotExist:
			raise Http404('Category doesn\'t exists.')


	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['heading'] = self.kwargs['category_title'].replace("-", " ").title() if self.kwargs.get('category_title') else 'Catalog'
		return context


class CategoryListView (ListView):
	model = Product
	paginate_by = 12
	template_name = 'store/list.html'

	def setup(self, request, *args, **kwargs):
		super().setup(request, *args, **kwargs)
		try:
			self.category: Category = Category.objects.get(category_id=self.kwargs['category_id'])
		except Category.DoesNotExist:
			raise Http404("Category does not exist")

	def get_queryset(self, **kwargs):
		if self.request.user.is_authenticated:
			return Product.products.filter(category__in=self.category.get_descendants(include_self=True)).annotate(
					is_wishlisted=Exists(
						Product.objects.filter(
							id=OuterRef('id'),
							wishlist=self.request.user
						)
					)
				)
		return Product.products.filter(category__in=self.category.get_descendants(include_self=True))

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['heading'] = self.category.title if self.category else False
		return context


class CollectionListView (ListView):
	model = Product
	paginate_by = 12
	template_name = 'store/list.html'

	def setup(self, request, *args, **kwargs):
		super().setup(request, *args, **kwargs)
		try:
			self.collection: Collection = Collection.objects.get(slug=self.kwargs['collection_slug'])
		except Collection.DoesNotExist:
			raise Http404("Category does not exist")

	def get_queryset(self, **kwargs):
		if self.request.user.is_authenticated:
			return Product.products.filter(collection=self.collection).annotate(
					is_wishlisted=Exists(
						Product.objects.filter(
							id=OuterRef('id'),
							wishlist=self.request.user
						)
					)
				)
		return Product.products.filter(collection=self.collection)

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['heading'] = self.collection.name if self.collection else False
		return context


class DiscountListView (ListView):
	model = Product
	paginate_by = 12
	template_name = 'store/list.html'

	def get_queryset(self):
		queryset = Product.products.filter(discount_price__isnull=False).exclude(discount_price=0)
		
		if self.request.user.is_authenticated:
			queryset = queryset.annotate(
				is_wishlisted=Exists(
					Product.objects.filter(
						id=OuterRef('id'),
						wishlist=self.request.user
					)
				)
			)
		return queryset

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['heading'] = False
		context['discount'] = True
		return context


class ProductDetailView (DetailView):
	model = Product
	template_name = 'store/product.html'

	def get_queryset(self):
		queryset = super().get_queryset()
		
		if self.request.user.is_authenticated:
			queryset = queryset.annotate(
				is_wishlisted=Exists(
					Product.objects.filter(
						id=OuterRef('id'),
						wishlist=self.request.user
					)
				)
			)
		return queryset


@rate_limit(limit=5, period=60)
@csrf_protect
def contact_view(request):
	if request.method != "POST":
		return JsonResponse({"error": "POST request required."}, status=405)

	# Check sender data
	try:
		data = json.loads(request.body)
	except json.JSONDecodeError as e:
		logger.error(f"Error in contact form submission: {str(e)}")
		return JsonResponse({"error": "Invalid JSON in request.body."}, status=400)

	form = ContactForm(data)

	# Validate contact form
	if form.is_valid():
		# process form data
		cleaned_data = form.cleaned_data
        # Send email
		message = f"""
        New contact form submission:
        Name: {cleaned_data['fname']} {cleaned_data['lname']}
        Email: {cleaned_data['email']}
        Message: {cleaned_data['message']}
        """
		send_mail('New Contact Form Submission', message, cleaned_data['email'], ['info@zubies.co'], fail_silently=False)
		return JsonResponse({"message": "Thankyou for contacting us."}, status=201)
	else:
		return JsonResponse({"error": form.errors}, status=400)

	# Create contact
	# contact = Contact(
	# 	fname=fname,
	# 	lname=lname,
	# 	phone_number=phone_number,
	# 	email=email,
	# 	message=message,
	# )
	# contact.save()

templates/store/index.html
{% extends './layout.html' %}
{% load static %}


{% block style %}
    <link rel="stylesheet" href="{% static 'css/store/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
	<style>
		.contact .contact-img-section {
			background-image: url('{% static "img/index/contact-side.webp" %}');
		}
	</style>
{% endblock %}

{% block body %}

	<!-- Carousel Start -->
	<div class="container-fluid carousel">
		<div class="text">
			<h1 class="animate-text">New Arrivals</h1>
			<p class="animate-text">We know you'll love!</p>
		</div>
		<a href="#" class="carousel-image">
			<img src="{% static 'img/index/carousel/arrival.webp' %}" alt="New Arrivals" decoding="async" loading="eager" fetchpriority="high">
		</a>
	</div>
	<!-- Carousel End -->

	<div class="divider"></div>
    
	<!-- Catalog Start -->
	<div class="container catalog">
		<h1>CATALOG</h1>
		<p>Explore our collection.</p>
		<div class="catalog-grid">
			<div class="catalog-grid-item appear"><a href="{% url 'store:catalog_category' category_title='men' %}"><img src="{% static 'img/index/catalog/img-1-3.webp' %}" alt="item 1" decoding="async" loading="lazy" fetchpriority="low"></a></div>
			<div class="catalog-grid-item appear"><a href="#" disabled><img src="{% static 'img/index/catalog/img-2.webp' %}" alt="item 2" decoding="async" loading="lazy" fetchpriority="low"></a></div>
			<div class="catalog-grid-item appear"><a href="#" disabled><img src="{% static 'img/index/catalog/img-3-1.webp' %}" alt="item 3" decoding="async" loading="lazy" fetchpriority="low"></a></div>
			<div class="catalog-grid-item appear"><a href="#" disabled><img src="{% static 'img/index/catalog/img-4-1.webp' %}" alt="item 4" decoding="async" loading="lazy" fetchpriority="low"></a></div>
			<div class="catalog-grid-item appear"><a href="{% url 'store:catalog_category' category_title='chelsea' %}"><img src="{% static 'img/index/catalog/img-5-1.webp' %}" alt="item 5" decoding="async" loading="lazy" fetchpriority="low"></a></div>
			<div class="catalog-grid-item"><a href="{% url 'store:catalog' %}" class="btn btn-explore appear">Explore More</a></div>
		</div>
	</div>
	<!-- Catalog End -->

	<div class="divider"></div>

	<!-- About Start -->
	<div class="container about">
		<h1>About</h1>
		<p>ZUBIES-where passion is the base and fashion is in every step, every single move articulates a story. Being amongst the latest brands, we are committed to fashioning stilettos and shoes that are extremely beautiful, where elegance combines with innovation.</p>
		<div class="about-img appear"><img src="{% static 'img/index/about/img-1.webp' %}" alt="leather shoe" decoding="async" loading="lazy" fetchpriority="low"></div>
		<p>We believe that every pair of shoes should be more than just an accessory; they should be a statement of style and individuality. Our team of designers and artisans is committed to creating high-quality footwear that combines timeless aesthetics with contemporary trends.</p>
		<h1>Store</h1>
		<p>Our journey began with a vision to revolutionize the footwear industry by offering designs that not only captivate but also inspire confidence. We invite you to go through our collections and experience the artistry and craftsmanship that define ZUBIES. Step into elegance and let your shoes make a difference.</p>
		<div class="about-img appear"><img src="{% static 'img/index/about/img-2.webp' %}" alt="stilettos" decoding="async" loading="lazy" fetchpriority="low"></div>
		<div class="btn-read-container"><a href="#" class="btn btn-read appear">Read More</a></div>
	</div>
	<!-- About End -->

	<div class="divider"></div>

	<!-- Subscribe Start -->
	<div class="container-fluid subscribe">
		<div class="subscribe-img"><img src="{% static 'img/index/subscribe1.webp' %}" alt="subsribe casual shoe background cover" decoding="async" loading="lazy" fetchpriority="low"></div>
		<h1>Subscribe</h1>
		<p>Subscribe now for exclusive updates, offers, and news delivered directly to your inbox!</p>
		<form method="post" id="form-subscribe">
			{% csrf_token %}
			<input type="email" name="email" placeholder="Your Email" required>
			<button type="submit">Subscribe</button>
		</form>
	</div>
	<!-- Subscribe End -->
    
	<div class="divider" id="contact-section"></div>

	<!-- Contact Us Start -->
	<div class="container contact">
		<p>Step into style, fall in love with every step.</p>
		<h1>Reach Out</h1>
		<form method="POST" id="contact-us" class="auth_form row">
			{% csrf_token %}
			<div class="col-12 col-md-6">
				<input type="text" class="form-control" name="fname" placeholder="First Name">
			</div>
			<div class="col-12 col-md-6">
				<input type="text" class="form-control" name="lname" placeholder="Last Name">
			</div>
			<div class="col-12"><input type="email" class="form-control" name="email" placeholder="Email"></div>
			<div class="col-12"><textarea name="message" class="form-control" placeholder="Message" rows="4"></textarea></div>
			<div class="col-12"><button type="submit" class="btn btn-continue">Send</button></div>
			<p class="form_message"></p>
		</form>
		<div class="contact-img-container">
			<div class="contact-img-section contact-img-left"></div>
			<div class="contact-img-section contact-img-center"></div>
			<div class="contact-img-section contact-img-right"></div>
		</div>
	</div>
	<!-- Contact Us End -->

	<div class="divider"></div>

{% endblock body %}


{% block script %}

	<!-- Preload critical carousel images -->
	<link rel="preload" as="image" href="{% static 'img/index/carousel/arrival.webp' %}" fetchpriority="high">
	<link rel="preload" as="image" href="{% static 'img/index/carousel/seasoned-1.webp' %}" fetchpriority="low">
	<link rel="preload" as="image" href="{% static 'img/index/carousel/discount-2.webp' %}" fetchpriority="low">
	<link rel="preload" as="image" href="{% static 'img/index/carousel/heels.webp' %}" fetchpriority="low">
	<script>
		// Define textOptions before index.js loads
		const textOptions = [
			{ h1: "New Arrivals", p: "We know you'll love!", img: "{% static 'img/index/carousel/arrival.webp' %}", href: "{% url 'store:products-by-collection' collection_slug='new-arrivals' %}" },
			{ h1: "Fall/Winter 24'", p: "Perfect for the season.", img: "{% static 'img/index/carousel/seasoned-1.webp' %}", href: "{% url 'store:products-by-collection' collection_slug='fallwinter-24' %}" },
			{ h1: "Flat 20% Sale", p: "Deals you can't miss!", img: "{% static 'img/index/carousel/discount-2.webp' %}", href: "{% url 'store:discount-products' %}" },
			{ h1: "Fall in Love", p: "Coming Soon: Women's Heels & Shoes!", img: "{% static 'img/index/carousel/heels.webp' %}" },
		];

		const contact_url = "{% url 'store:contact-us' %}";
		const subscribe_url = "{% url 'more:subscribe' %}";
	</script>
	<script src="{% static 'js/store/index.js' %}" data-rel-js></script>
{% endblock script %}

templates/store/list.html
{% extends 'store/layout.html' %}
{% load static %}

{% block title %}
	{{ heading | title }} 
	{% if subheading %}
		- {{ subheading | title }}
	{% endif %}
{% endblock title %}

{% block style %}
	<link rel="stylesheet" href="{% static 'css/store/products.css' %}">
{% endblock style %}

{% block body %}
<div class="container-fluid px-md-5 mt-5 h-100">
	<h1 class="text-center">
		{% if heading %}
			{{ heading | title }}
		{% endif %}
		{% if subheading %}
			- {{ subheading | title }}
		{% endif %}
	</h1>
	<section class="products">
		<div class="row place row-cols-1 {% if object_list|length > 0 %} row-cols-sm-2 row-cols-lg-3 row-cols-xxl-4 g-4 g-xl-5 {% endif %} mx-md-5 my-2">
			{% for item in object_list %}
				<div class="col">
					<div class="card position-relative p-3">
						<div class="h-100 w-100 position-relative">
							<div class="product-img-container">
								{% if item.get_images %}
									{% with image=item.get_images.0.image %}
										<img src="{{ image.url }}" width="370" alt="{{ image.alt_text }}" >
									{% endwith %}
								{% else %}
									No Image
								{% endif %}
							</div>
							<a href="{{ item.get_absolute_url }}" class="card-body d-none d-md-grid">
								<h2 class="card-title h5">{{ item.title | title }}</h2>
								{% if item.discount_price %}
									<span class="d-flex gap-2 justify-content-center"><del>Rs. {{ item.regular_price|floatformat }}</del> Rs. {{ item.discount_price|floatformat }}</span>
								{% else %}
									Rs. {{ item.regular_price|floatformat }}
								{% endif %}
							</a>
							<div class="card-body d-grid d-md-none">
								<h2 class="card-title h5">{{ item.title | title }}</h2>
								{% if item.discount_price %}
									<span class="d-flex gap-2 justify-content-center"><del>Rs. {{ item.regular_price|floatformat }}</del> Rs. {{ item.discount_price|floatformat }}</span>
								{% else %}
									Rs. {{ item.regular_price|floatformat }}
								{% endif %}

								<a href="{{ item.get_absolute_url }}" class="btn btn-secondary explore-btn w-fit-content fs-5 px-5 mt-3 mx-auto fw-semibold">Explore</a>
							</div>
							<!-- <a href="{% url 'account:add-to-wishlist' item.slug %}" class="wishlist_icon position-absolute text-success bottom-0 end-0 translate-middle">
								{% if item in wishlist_listings %}
									<ion-icon name="heart"></ion-icon>
								{% else %}
									<ion-icon name="heart-outline"></ion-icon>
								{% endif %}
							</a> -->
						</div>
					</div>
				</div>
			{% empty %}
				{% if discount %}
					<h2 class="text-center my-4">No Discount Available</h2>
				{% elif heading %}
					<h2 class="text-center mb-5">Coming Soon</h2>
				{% else %}
					<h2 class="text-center mt-5 mb-4">404 Not Found</h2>
				{% endif %}
				<a href="{% url 'store:index' %}" class="btn btn-primary w-fit-content px-5 mx-auto">Back to Home</a>
			{% endfor %}
		</div>
								<!-- PAGINATION START -->
		{% if is_paginated %}
			<nav aria-label="Page navigation example">
				<ul class="pagination justify-content-center">
					{% if page_obj.has_previous %}
						<li class="page-item">
							<a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
					{% else %}
						<li class="page-item disabled">
							<a class="page-link" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
					{% endif %}
					{% for i in page_obj.paginator.get_elided_page_range %}
						{% if page_obj.paginator.ELLIPSIS == forloop.counter %}
							<li class="page-item disabled"><a class="page-link" href="#">{{ forloop.counter }}</a></li>
						{% else %}
							{% if page_obj.number == forloop.counter %}
								<li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
							{% else %}
								<li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
							{% endif %}
						{% endif %}
					{% endfor %}
					{% if page_obj.has_next %}
						<li class="page-item">
							<a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					{% else %}
						<li class="page-item disabled">
							<a class="page-link" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					{% endif %}
				</ul>
			</nav>
		{% endif %}
								<!-- PAGINATION END -->
	</section>
</div>
{% endblock body %}

templates/store/products.html
{% extends 'store/layout.html' %}
{% load static %}

{% block title %}
	{{ heading | title }} 
	{% if subheading %}
		- {{ subheading | title }}
	{% endif %}
{% endblock title %}

{% block style %}
	<link rel="stylesheet" href="{% static 'css/store/products.css' %}">
{% endblock style %}

{% block body %}
<div class="container-fluid px-md-5 mt-5 h-100">
	<h1 class="text-center">
		{% if heading %}
			{{ heading | title }}
		{% endif %}
		{% if subheading %}
			- {{ subheading | title }}
		{% endif %}
	</h1>
	<section class="products">
		<div class="row place row-cols-1 {% if object_list|length > 0 %} row-cols-sm-2 row-cols-lg-3 row-cols-xxl-4 g-4 g-xl-5 {% endif %} mx-md-5 my-2">
			{% for item in object_list %}
				<div class="col">
					<div class="card position-relative p-3">
						<div class="h-100 w-100 position-relative">
							<div class="product-img-container">
								{% if item.get_images %}
									{% with image=item.get_images.0.image %}
										<img src="{{ image.url }}" width="370" alt="{{ image.alt_text }}" >
									{% endwith %}
								{% else %}
									No Image
								{% endif %}
							</div>
							<a href="{{ item.get_absolute_url }}" class="card-body d-none d-md-grid">
								<h2 class="card-title h5">{{ item.title | title }}</h2>
								{% if item.discount_price %}
									<span class="d-flex gap-2 justify-content-center"><del>Rs. {{ item.regular_price|floatformat }}</del> Rs. {{ item.discount_price|floatformat }}</span>
								{% else %}
									Rs. {{ item.regular_price|floatformat }}
								{% endif %}
							</a>
							<div class="card-body d-grid d-md-none">
								<h2 class="card-title h5">{{ item.title | title }}</h2>
								{% if item.discount_price %}
									<span class="d-flex gap-2 justify-content-center"><del>Rs. {{ item.regular_price|floatformat }}</del> Rs. {{ item.discount_price|floatformat }}</span>
								{% else %}
									Rs. {{ item.regular_price|floatformat }}
								{% endif %}

								<a href="{{ item.get_absolute_url }}" class="btn btn-secondary explore-btn w-fit-content fs-5 px-5 mt-3 mx-auto fw-semibold">Explore</a>
							</div>
							<!-- <a href="{% url 'account:add-to-wishlist' item.slug %}" class="wishlist_icon position-absolute text-success bottom-0 end-0 translate-middle">
								{% if item in wishlist_listings %}
									<ion-icon name="heart"></ion-icon>
								{% else %}
									<ion-icon name="heart-outline"></ion-icon>
								{% endif %}
							</a> -->
						</div>
					</div>
				</div>
			{% empty %}
				{% if discount %}
					<h2 class="text-center my-4">No Discount Available</h2>
				{% elif heading %}
					<h2 class="text-center mb-5">Coming Soon</h2>
				{% else %}
					<h2 class="text-center mt-5 mb-4">404 Not Found</h2>
				{% endif %}
				<a href="{% url 'store:index' %}" class="btn btn-primary w-fit-content px-5 mx-auto">Back to Home</a>
			{% endfor %}
		</div>
								<!-- PAGINATION START -->
		{% if is_paginated %}
			<nav aria-label="Page navigation example">
				<ul class="pagination justify-content-center">
					{% if page_obj.has_previous %}
						<li class="page-item">
							<a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
					{% else %}
						<li class="page-item disabled">
							<a class="page-link" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						</li>
					{% endif %}
					{% for i in page_obj.paginator.get_elided_page_range %}
						{% if page_obj.paginator.ELLIPSIS == forloop.counter %}
							<li class="page-item disabled"><a class="page-link" href="#">{{ forloop.counter }}</a></li>
						{% else %}
							{% if page_obj.number == forloop.counter %}
								<li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
							{% else %}
								<li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
							{% endif %}
						{% endif %}
					{% endfor %}
					{% if page_obj.has_next %}
						<li class="page-item">
							<a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					{% else %}
						<li class="page-item disabled">
							<a class="page-link" aria-label="Next">
								<span aria-hidden="true">&raquo;</span>
							</a>
						</li>
					{% endif %}
				</ul>
			</nav>
		{% endif %}
								<!-- PAGINATION END -->
	</section>
</div>
{% endblock body %}