address/urls.py
from django.urls import path

from . import views

app_name = 'address'

urlpatterns = [
	path("", views.address_list, name="addresses"),
	path("session-update", views.address_session_view, name="address-session-update"),
	path("add/", views.add_address, name="add_address"),
	path("edit/<uuid:id>", views.edit_address, name="edit_address"),
	path("delete/<uuid:id>", views.delete_address, name="delete_address"),
	path("set_default/<uuid:id>", views.default_address, name="set_default"),
]

checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'

urlpatterns = [
	path('', views.CheckoutView, name='checkout'),
	path('update-delivery-charges', views.UpdateDeliveryChargesInBasket, name='update-dc-in-basket')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("account/", include("account.urls", namespace="account")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("more/", include("more.urls", namespace="more")),
    path("order/", include("order.urls", namespace="order")),
    path("address/", include("address.urls", namespace="address")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("__reload__/", include("django_browser_reload.urls")),
]

# add at the last
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
	path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
	path('order_placement/', views.Order_placement, name='order-placement'),
	# orders history
	path('orders-history/', views.orders_history, name="orders-history"),
	# order cancel
	path('cancel-order/', views.order_cancel, name='order-cancel'),
	# order item cancel/remove
	path('order-item-remove/', views.order_item_remove, name='order-item-remove'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
	# Home Url
	path('', views.HomeView.as_view(), name='index'),

	# Catalog Url
	path('catalog/', views.CatalogView.as_view(), name='catalog'),
	path('catalog/<str:category_title>/', views.CatalogView.as_view(), name='catalog_category'),
	# Category Url
	path('category/<uuid:category_id>/', views.CategoryListView.as_view(), name='products-by-category'),
	# Features Url
	path('collection/<slug:collection_slug>/', views.CollectionListView.as_view(), name='products-by-collection'),
	# Discount Url
	path('discount/', views.DiscountListView.as_view(), name='discount-products'),

	# Product Detail Url
	path('product/<slug>/', views.ProductDetailView.as_view(), name='product'),

	# About Us Url
	path('about-us/', views.AboutView.as_view(), name='about-us'),
	# Contact Us API Url
	path('contact/', views.contact_view, name='contact-us')
]

order/models.py
import uuid
from django.conf import settings
from django_countries.fields import CountryField
from django.db import models
from django.utils import timezone

from store.models import Product, ProductSpecificationValue

# Create your models here.


class Order(models.Model):
	ORDER_STATUS_CHOICES = (
		("F", "Fullfilled"),
		("P", "In Process"),
		("C", "Is Cancelled"),
	)
	DELIVERY_STATUS_CHOICES = (
		("D", "Delivered"),
		("P", "In Process"),
		("C", "Is Cancelled"),
	)

	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

	user = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		related_name="order",
		blank=True,
		null=True,
	)
	items = models.ManyToManyField("store.Product", through='OrderItem')

	# payment
	total_payment = models.DecimalField(max_digits=10, decimal_places=2)
	paid = models.BooleanField(default=False)
	PAYMENT_CHOICES = (("COD", "Cash on Delivery"),)
	payment = models.CharField(max_length=15, choices=PAYMENT_CHOICES, default="COD")

	# order
	order_created = models.DateTimeField(auto_now_add=True)
	order_updated = models.DateTimeField(auto_now=True)
	order_status = models.CharField(
		max_length=2, choices=ORDER_STATUS_CHOICES, default="P"
	)

	# cancel
	is_cancelled = models.BooleanField(default=False)

	# delivery
	delivery_status = models.CharField(
		max_length=2, choices=DELIVERY_STATUS_CHOICES, default="P"
	)
	delivered_date = models.DateTimeField(blank=True, null=True)
	delivered = models.BooleanField(default=False)

	# billing address details
	# required
	first_name = models.CharField(max_length=25)
	last_name = models.CharField(max_length=25)
	email = models.EmailField()
	# optional, that if billing address exits then no need to reenter data into these fields
	phone_number = models.CharField(max_length=15, blank=True, null=True)
	address_line_1 = models.CharField(max_length=150, blank=True, null=True)
	address_line_2 = models.CharField(max_length=150, blank=True, null=True)
	city = models.CharField(max_length=150, blank=True, null=True)
	state = models.CharField(max_length=150, blank=True, null=True)
	country = CountryField(blank_label="Country", blank=True, null=True)
	zip_code = models.CharField(max_length=12, blank=True, null=True)

	class Meta:
		ordering = ("-order_created",)
	
	def __str__(self):
		if self.user:
			f_name = self.user.first_name
			l_name = self.user.last_name
		else:
			f_name = self.first_name
			l_name = self.last_name
		order_placed = self.order_created.strftime("%I:%M %p | %d-%m-%Y")
		return f"{f_name} {l_name} | {order_placed}"

	def can_be_cancelled(self):
		return (timezone.now() - self.order_created).total_seconds() <= 12 * 60 *60



class OrderItem(models.Model):
	order = models.ForeignKey(
		Order,
		on_delete=models.CASCADE,
		related_name="order_items"
	)
	item = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
	quantity = models.IntegerField(default=1)
	is_cancelled = models.BooleanField(default=False)

	def __str__(self):
		if self.is_cancelled:
			option = 'Cancelled'
		else:
			option = ', '.join(str(attr) for attr in self.order_item_attribute.all())
		return f"{self.order.id} ----- {self.quantity} of {self.item.title} ----- {option}"


class OrderItemAttribute(models.Model):
	order_item = models.ForeignKey(OrderItem, on_delete=models.CASCADE, related_name="order_item_attribute")
	attribute = models.ForeignKey(ProductSpecificationValue, on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.attribute.specification.name}: {self.attribute.value}'

address/forms.py
from django import forms

from .models import BillingAddress


class UserAddressForm(forms.ModelForm):
	class Meta:
		model = BillingAddress
		fields = "__all__"
		exclude = ("customer", "default")

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field_name in self.fields:
			self.fields[field_name].widget.attrs.update(
				{
					"class": "form-control mb-2",
					"placeholder": field_name.replace("_", " ").title(),
				}
			)
		self.fields["country"].widget.attrs.update(
			{
				"class": "form-select",
			}
		)
		self.fields["city"].widget.attrs.update(
			{
				"class": "form-select",
			}
		)


class BillingForm(forms.ModelForm):
	first_name = forms.CharField(
		label="First Name",
		min_length=4,
		max_length=50,
		widget=forms.TextInput(
			attrs={
				"class": "form-control",
				"placeholder": "First Name",
			}
		),
	)
	last_name = forms.CharField(
		label="Last Name",
		min_length=4,
		max_length=50,
		widget=forms.TextInput(
			attrs={
				"class": "form-control",
				"placeholder": "Last Name",
			}
		),
	)
	email = forms.EmailField(
		label="Email",
		max_length=200,
		widget=forms.EmailInput(
			attrs={
				"class": "form-control mb-3",
				"placeholder": "email",
			}
		),
	)
	save_info = forms.BooleanField(
		label="Save this information for next time",
		required=False,
		widget=forms.CheckboxInput(),
	)
	PAYMENT_CHOICES = [
		("COD", "Cash on Delivery"),
	]

	payment_method = forms.ChoiceField(
		choices=PAYMENT_CHOICES,
		widget=forms.RadioSelect(
			attrs={
				"checked": "checked",
			}
		), label="Payment Method"
	)

	class Meta:
		model = BillingAddress
		fields = "__all__"
		exclude = ("user",)

		labels = {
			"address_line_1": "Address",
			"address_line_2": "Address 2",
			"state": "State/Province/Region",
		}

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields["phone_number"].widget.attrs.update(
			{
				"class": "form-control",
				"placeholder": "Phone number",
			}
		)
		self.fields["address_line_1"].widget.attrs.update(
			{
				"class": "form-control",
				"placeholder": "Address",
			}
		)
		self.fields["address_line_2"].widget.attrs.update(
			{"class": "form-control", "placeholder": "Address 2"}
		)
		self.fields["city"].widget.attrs.update(
			{"class": "form-select", "placeholder": "City"}
		)
		self.fields["state"].widget.attrs.update(
			{"class": "form-control", "placeholder": "State"}
		)
		self.fields["country"].widget.attrs.update(
			{"class": "form-select", "placeholder": "Country"}
		)
		self.fields["zip_code"].widget.attrs.update(
			{"class": "form-control", "placeholder": "Zip Code"}
		)

checkout/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.contrib import messages

from address.forms import BillingForm
from address.models import BillingAddress
from address.billingaddress import Billing

from .models import DeliveryOptions
from basket.basket import Basket


def CheckoutView(request):
	"""
	Order checkout to add address.
	"""
	billing_session = Billing(request)
	basket = Basket(request)
	basketqty = basket.__len__()
	if basketqty <= 0:
		messages.error(request, "Your basket is empty.")
		return redirect("store:index")

	delivery_options = DeliveryOptions.objects.filter(is_active=True)

	if request.POST:
		if request.user.is_authenticated:
			try:
				billing = BillingAddress.objects.get(
					customer=request.user, default=True
				)
				bform = BillingForm(request.POST, instance=billing)
			except ObjectDoesNotExist:
				bform = BillingForm(request.POST)

			if bform.is_valid():
				if bform.cleaned_data["save_info"]:
					billingsave = bform.save(commit=False)
					billingsave.customer = request.user
					billingsave.default = True
					billingsave.save()
				billing_session.add(bform, request.user.id)
			else:
				return render(request, "checkout/checkout.html", {"form": bform, 'delivery_options': delivery_options})
		else:
			bform = BillingForm(request.POST)
			if bform.is_valid():
				billing_session.add(bform, "Anonymous")
			else:
				return render(request, "checkout/checkout.html", {"form": bform, 'delivery_options': delivery_options})

		return HttpResponseRedirect(reverse("order:order-placement"))
	else:
		if request.user.is_authenticated:
			try:
				address = BillingAddress.objects.get(
					customer=request.user, default=True
				)
				return render(
					request, "checkout/checkout.html", {"address": address, 'delivery_options': delivery_options}
				)

			except ObjectDoesNotExist:
				bform = BillingForm(
					initial={
						"first_name": request.user.first_name,
						"last_name": request.user.last_name,
						"email": request.user.email,
					}
				)
		elif billing_session.__len__() != 0:
			billing_address = billing_session.billing_address["Anonymous"]
			bform.initial = {
				"first_name": billing_address["first_name"],
				"last_name": billing_address["last_name"],
				"email": billing_address["email"],
				"phone_number": billing_address["phone_number"],
				"address_line_1": billing_address["address_line_1"],
				"address_line_2": billing_address["address_line_2"],
				"city": billing_address["city"],
				"state": billing_address["state"],
				"country": billing_address["country"],
				"zip_code": billing_address["zip_code"],
			}
		else:
			bform = BillingForm()
		
		return render(request, "checkout/checkout.html", {"form": bform, 'delivery_options': delivery_options})


def UpdateDeliveryChargesInBasket(request):
	basket = Basket(request)

	if request.POST.get('action') == 'post':
		delivery_option_id = int(request.POST.get('delivery_option_id'))
		city = request.POST.get('city')
		delivery_option = DeliveryOptions.objects.get(id=delivery_option_id)

		if city == 'lhr':
			dc = delivery_option.within_city_dc
		else:
			dc = delivery_option.other_city_dc

		basket.add_delivery_charges(dc)
		
		response = JsonResponse({'dc': dc, 'total_price': basket.get_total_price()})
		return response

order/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import (
	redirect,
	render,
	get_object_or_404,
)
from django.contrib.auth.decorators import login_required

from .models import Order, OrderItem, OrderItemAttribute

from store.models import Product, ProductSpecificationValue

from address.billingaddress import Billing

from basket.basket import Basket


def Order_placement(request):
	"""
	Orders and Orderitems are fetched from basket_session if exist, and are stored in actual order and orderitem models respectively.
	Then if billing address exists in databases, then it's attached to the order otherwise billing address details are fetched from billing_session and stored respectively in order.
	At last basket_session is cleared but not billing_session so can be used next time the user places order(s)
	"""
	basket_session = Basket(request)
	basketqty = basket_session.__len__()
	if basketqty <= 0:
		messages.error(request, "Your basket is empty.")
		return redirect("store:index")

	billing_session = Billing(request)
	if billing_session.__len__() != 0:
		billing_address = billing_session.billing_address[
			str(request.user.id) if request.user.is_authenticated else "Anonymous"
		]
	else:
		messages.error(request, "You have not filled billing details")
		return redirect("checkout:checkout")

	order = Order.objects.create(
		user=request.user if request.user.is_authenticated else None,
		total_payment=basket_session.get_total_price(),
	)
	order.phone_number = billing_address["phone_number"]
	order.address_line_1 = billing_address["address_line_1"]
	order.address_line_2 = billing_address["address_line_2"]
	order.city = billing_address["city"]
	order.state = billing_address["state"]
	order.country = billing_address["country"]
	order.zip_code = billing_address["zip_code"]
	order.first_name = billing_address["first_name"]
	order.last_name = billing_address["last_name"]
	order.email = billing_address["email"]

	order.save()

	for item in basket_session:
		prdt = get_object_or_404(Product, id=item["product"].get("id"))
		order_item = OrderItem.objects.create(
			item=prdt,
			order=order,
			quantity=item["qty"],
		)
		key = item['product'].get('key').split('-')[1:]
		attributes = ProductSpecificationValue.objects.filter(id__in=key)
		if attributes.exists():
			for attribute in attributes:
				OrderItemAttribute.objects.create(order_item=order_item, attribute=attribute)
		# order.items.add(order_item)

	basket_session.clear()

	messages.success(
		request, "Thanks for shopping! Your order has been placed successfully."
	)
	return redirect("store:index")


@login_required
def remove_from_cart(request, slug):
	item = get_object_or_404(Product, slug=slug)
	order_qs = Order.objects.filter(user=request.user, ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		# check if the order item is in the order
		if order.items.filter(item__slug=item.slug).exists():
			order_item = OrderItem.objects.filter(
				item=item, user=request.user, ordered=False
			)[0]
			order_item.quantity = 1
			order_item.save()
			order.items.remove(order_item)
			messages.success(
				request, f"{order_item.item.title} item was removed from your cart."
			)
		else:
			# add a message saying the user doesn't have an order
			messages.error(request, "This item was not in your cart.")
			return redirect("order:product", slug=slug)

	else:
		# add a message saying the user doesn't have an order
		messages.error(request, "You do not have an active order.")
		return redirect("order:product", slug=slug)
	return redirect("order:order-summary")


@login_required
def orders_history(request):
	orders = Order.objects.filter(user=request.user.id)
	return render(request, 'order/orders_history.html', {
		'orders': orders
	})


@login_required
def order_cancel(request):
	"""
	Cancel Order using order_id if time_stamp is within one day i.e., on the same day order was created
	"""
	if request.POST.get('action') == 'cancel':
		order_id = request.POST.get('order_id')
		order = Order.objects.get(pk=order_id)
		order.is_cancelled = True
		order.order_status = 'C'
		order.save()
		response = JsonResponse({'message': 'Order has been successfully cancelled', 'order_status': order.get_order_status_display()})
	return response


@login_required
def order_item_remove(request):
	"""
	Remove Order Item using item_id if time_stamp is within one day i.e., on the same day order was created
	"""
	if request.POST.get('action') == 'remove':
		item_id = request.POST.get('item_id')
		orderitem = OrderItem.objects.get(pk=item_id)
		orderitem.is_cancelled = True
		orderitem.save()

		order = Order.objects.get(order_items=orderitem)
		order_item_objects = OrderItem.objects.filter(order=order, is_cancelled=False)
		if not order_item_objects.exists():
			order.is_cancelled = True
			order.order_status = 'C'
			order.save()
		response = JsonResponse({'message': 'Order item has been successfully remove', 'cancelled': order.is_cancelled})

		return response

templates/order/checkout.html
{% extends 'store/layout.html' %}

{% block title %}Checkout{% endblock %}

{% block style %}
<style>
	.title+small,
	.title+small+span {
		color: wheat;
	}
</style>
{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row no-gutter">
		<div class="col-7 col-lg-4 order-lg-last mt-4 m-auto">
			<h4 class="d-flex justify-content-between align-items-center mb-3">
				<span style="color: wheat;">Your cart</span>
				<span class="badge rounded-pill" style="background: wheat; color: initial;">
					{% with total_qty=basket|length %}
					<span class="basket-qty d-inline-flex">{{ total_qty }}</span>
					{% endwith %}
				</span>
			</h4>
			<ul class="list-group py-3 px-2 mb-3 checkout-list rounded-4">
				{% for item in basket %}
				{% with product=item.product %}
				<li class="list-group-item d-flex justify-content-between lh-sm">
					<div>
						<h6 class="my-0">{{ product.title }}</h6>
						<small class="text-body-secondary">{{ product.description | truncatechars:30 }}</small>
					</div>
					<span class="text-body-secondary">Rs. {{ item.total_price }} ({{ item.qty }})</span>
				</li>
				{% endwith %}
				{% endfor %}

				<li class="list-group-item d-flex justify-content-between" style="color: wheat;">
					<span>Sub Total (PKR)</span>
					<strong>Rs. {{ basket.get_before_discount }}</strong>
				</li>
				<li class="list-group-item d-flex justify-content-between bg-body-tertiary">
					{% if basket.get_discount_price > 0 %}
					<div class="text-success">
						<h6 class="my-0">Discount</h6>
						<small>Special Discount for You</small>
					</div>
					<span class="text-success">−Rs. {{ basket.get_discount_price }}</span>
					{% else %}
					<div class="text-danger">
						<h6 class="my-0">Discount</h6>
						<small>Sorry! No discount available</small>
					</div>
					<span class="text-danger">Rs. {{ basket.get_discount_price }}</span>
					{% endif %}
				</li>

				<li class="list-group-item d-flex justify-content-between" style="color: wheat;">
					<span>Total (PKR)</span>
					<strong>Rs. {{ basket.get_total_price }}</strong>
				</li>
			</ul>

			{% if not form %}
			<a href="{% url 'order:order-placement' %}" class="btn basket w-100">Confirm Order</a>
			{% endif %}
		</div>
		{% if form %}
		<div class="col-lg-8">
			<div class="d-flex align-items-center py-4 pb-5">
				<div class="container">
					<div class="row">
						<div class="auth_form col-12 col-lg-11 mx-auto">
							<form action="" class="rounded mx-auto p-4 col-lg-10" method="post">
								{% csrf_token %}
								<h3 class="mb-2">Billing Address</h3>
								<!-- <p class="mb-4 text-muted">It's free and only takes a minute.</p> -->

								{% if form.errors %}
								<p class="text-danger">Please correct the following errors:</p>
								{% for field in form %}
								{% if field.errors %}
								<div class="alert alert-danger alert-dismissible fade show" role="alert">
									{{ field.label }}: {{ field.errors | striptags }}
									<button type="button" class="btn-close" data-bs-dismiss="alert"
										aria-label="Close"></button>
								</div>
								{% endif %}
								{% endfor %}
								{% endif %}

								<div class="row">
									<div class="col">
										<label for="id_first_name">{{ form.first_name.label }}</label>
										{{ form.first_name }}
									</div>
									<div class="col">
										<label for="id_last_name">{{ form.last_name.label }}</label>
										{{ form.last_name }}
									</div>
								</div>
								<div class="row">
									<div class="col">
										<label for="id_email">{{ form.email.label }} <span
												class="text-muted small">(Optional)</span></label>
										{{ form.email }}
									</div>
									<div class="col">
										<label for="id_phone_number">{{ form.phone_number.label }}</label>
										{{ form.phone_number }}
									</div>
								</div>
								<div class="row">
									<div class="col">
										<label for="id_address_line_1">{{ form.address_line_1.label }}</label>
										{{ form.address_line_1 }}
									</div>
									<div class="col">
										<label for="id_address_line_2">{{ form.address_line_2.label }} <span
												class="text-muted small">(Optional)</span></label>
										{{ form.address_line_2 }}
									</div>
								</div>
								<div class="row">
									<div class="col">
										<label for="id_city">{{ form.city.label }}</label>
										{{ form.city }}
									</div>
									<div class="col">
										<label for="id_state">{{ form.state.label }}</label>
										{{ form.state }}
									</div>
									<div class="col">
										<label for="id_country">{{ form.country.label }}</label>
										{{ form.country }}
									</div>
									<div class="col">
										<label for="id_zip_code">{{ form.zip_code.label }}</label>
										{{ form.zip_code }}
									</div>
								</div>
								{% if user.is_authenticated %}
								<hr>
								{{ form.save_info }}
								<label for="id_save_info" style="cursor: pointer;">{{ form.save_info.label }}</label>
								{% endif %}
								<hr class="mt-0">

								<label for="id_payment_method" class="h3">{{ form.payment_method.label }}</label>
								{{ form.payment_method }}

								<hr>

								<input class="btn w-100" type="submit" value="Confirm Order">
								<p class="text-center">Back to <a href="{% url 'store:index' %}">home</a></p>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		{% else %}
		<div class="col-7 col-lg-3 me-lg-0 p-0 order-first mt-4 m-auto">
			<h4 class="d-flex justify-content-between align-items-center mb-3">
				<span style="color: wheat;">Your Default Address</span>
				<span class="badge rounded-pill" style="background: wheat; color: initial;">
					<span class="basket-qty d-inline-flex">Label</span>
				</span>
			</h4>
			<ul class="list-group py-3 px-2 mb-3 checkout-list rounded-4">
				<li class="list-group-item d-flex justify-content-between lh-sm">
					<div>
						<h6 class="my-0 title">Name</h6>
						<small class="text-body-secondary">{{ address.first_name }} {{ address.last_name }}</small>
					</div>
				</li>
				<li class="list-group-item d-flex justify-content-between lh-sm">
					<div>
						<h6 class="my-0 title">Phone Number</h6>
						<small class="text-body-secondary">{{ address.phone_number }}</small>
					</div>
				</li>
				<li class="list-group-item d-flex justify-content-between lh-sm">
					<div>
						<h6 class="my-0 title">Email</h6>
						<small class="text-body-secondary">{{ address.email }}</small>
					</div>
				</li>
				<li class="list-group-item d-flex justify-content-between lh-sm">
					<div>
						<h6 class="my-0 title">Address</h6>
						<small class="text-body-secondary">{{ address.address_line_1 }}</small>
					</div>
				</li>
				{% if address.address_line_2 %}
				<li class="list-group-item d-flex justify-content-between lh-sm">
					<div>
						<h6 class="my-0 title">Address</h6>
						<small class="text-body-secondary">{{ address.address_line_2 }}</small>
					</div>
				</li>
				{% endif %}
				<li class="list-group-item d-flex justify-content-between lh-sm">
					<div>
						<h6 class="my-0 title">Area</h6>
						<small class="text-body-secondary">{{ address.city }}, {{ address.get_country_display }}</small>
					</div>
					<span class="text-body-secondary">{{ address.zip_code }}</span>
				</li>
			</ul>
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}

{% block script %}
{% if not form %}
<script>
	$(document).ready(function () {
		var csrfToken = "{{ csrf_token }}";
		$.ajax({
			type: "post",
			url: "{% url 'address:address-session-update' %}",
			data: {
				csrfmiddlewaretoken: csrfToken,
				action: 'post'
			},
			success: function (response) {
				console.log(response)
			},
			error: function (xhr, errmessage, err) {
				console.log('error occurred')
				console.log(err)
			}
		});
	});
</script>
{% endif %}
{% endblock %}