address/urls.py
from django.urls import path

from . import views

app_name = 'address'

urlpatterns = [
	path("", views.address_list, name="addresses"),
	path("session-update", views.address_session_view, name="address-session-update"),
	path("add/", views.add_address, name="add_address"),
	path("edit/<uuid:id>", views.edit_address, name="edit_address"),
	path("delete/<uuid:id>", views.delete_address, name="delete_address"),
	path("set_default/<uuid:id>", views.default_address, name="set_default"),
]

checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'

urlpatterns = [
	path('', views.CheckoutView, name='checkout'),
	path('update-delivery-charges', views.UpdateDeliveryChargesInBasket, name='update-dc-in-basket')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("account/", include("account.urls", namespace="account")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("more/", include("more.urls", namespace="more")),
    path("order/", include("order.urls", namespace="order")),
    path("address/", include("address.urls", namespace="address")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
    path("__reload__/", include("django_browser_reload.urls")),
]

# add at the last
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
	# Home Url
	path('', views.HomeView.as_view(), name='index'),

	# Catalog Url
	path('catalog/', views.CatalogView.as_view(), name='catalog'),
	path('catalog/<str:category_title>/', views.CatalogView.as_view(), name='catalog_category'),
	# Category Url
	path('category/<uuid:category_id>/', views.CategoryListView.as_view(), name='products-by-category'),
	# Features Url
	path('collection/<slug:collection_slug>/', views.CollectionListView.as_view(), name='products-by-collection'),
	# Discount Url
	path('discount/', views.DiscountListView.as_view(), name='discount-products'),

	# Product Detail Url
	path('product/<slug>/', views.ProductDetailView.as_view(), name='product'),

	# About Us Url
	path('about-us/', views.AboutView.as_view(), name='about-us'),
	# Contact Us API Url
	path('contact/', views.contact_view, name='contact-us')
]

address/models.py
import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from django.conf import settings


class BillingAddress (models.Model):
	CITY_CHOICES = (
		("", "City"),
		("abd", "Attock"),
		("abt", "Abbottabad"),
		("bhr", "Bahawalnagar"),
		("bwn", "Bhawana"),
		("bhk", "Bhakkar"),
		("bwp", "Bahawalpur"),
		("cwp", "Chishtian"),
		("dgh", "Dera Ghazi Khan"),
		("dnb", "Dinawali"),
		("dip", "Dipalpur"),
		("fdr", "Fateh Jhang"),
		("fsl", "Faisalabad"),
		("ghk", "Gujar Khan"),
		("gjr", "Gujranwala"),
		("grk", "Gwadar"),
		("grw", "Gujranwala"),
		("gjr", "Gujrat"),
		("hyd", "Hyderabad"),
		("isl", "Islamabad"),
		("jlm", "Jalalpur"),
		("jwn", "Jaranwala"),
		("jwp", "Jhelum"),
		("khr", "Khairpur"),
		("khi", "Karachi"),
		("khr", "Khanewal"),
		("ktt", "Kotli"),
		("kwb", "Kot Adu"),
		("lai", "Lalamusa"),
		("lhr", "Lahore"),
		("ldr", "Lodhran"),
		("lrd", "Larkana"),
		("ltr", "Layyah"),
		("mll", "Mian Channu"),
		("mlk", "Malakwal"),
		("mlt", "Mardan"),
		("mrd", "Multan"),
		("mnt", "Mansehra"),
		("mgw", "Mandi Bahauddin"),
		("mwm", "Mianwali"),
		("mtr", "Multan"),
		("mzt", "Murree"),
		("mzw", "Muzaffargarh"),
		("ngt", "Narowal"),
		("nwn", "Nankana Sahib"),
		("pwp", "Peshawar"),
		("phl", "Pattoki"),
		("qta", "Quetta"),
		("qrb", "Quetta Residency"),
		("rch", "Rajanpur"),
		("rnw", "Rawalpindi"),
		("rkn", "Rahim Yar Khan"),
		("rwp", "Rawalpindi"),
		("sgr", "Sargodha"),
		("skt", "Sialkot"),
		("shw", "Sheikhupura"),
		("swn", "Swat"),
		("sak", "Sargodha"),
		("sbq", "Sahiwal"),
		("ska", "Sakrand"),
		("skz", "Sukheki"),
		("stw", "Sialkot"),
		("suk", "Sukkur"),
		("swl", "Sahiwal"),
		("sgr", "Sargodha"),
		("swl", "Sialkot"),
		("saw", "Sawat"),
		("ttn", "Toba Tek Singh"),
		("vhn", "Vehari"),
		("wah", "Wah Cantt"),
		("wln", "Wazirabad"),
	)

	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	# Customer
	customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_("Customer"), blank=True, null=True)
	first_name = models.CharField(_("First Name"), max_length=150)
	last_name = models.CharField(_("Last Name"), max_length=150)
	email = models.EmailField()
	# Delivery Details
	phone_number = models.CharField(_("Phone Number"), max_length=15)
	address_line_1 = models.CharField(_("Address Line 1"), max_length=150)
	address_line_2 = models.CharField(_("Address Line 2"), max_length=150, blank=True)
	city = models.CharField(_("City"), choices=CITY_CHOICES, max_length=150)
	state = models.CharField(_("State/Province"), max_length=150)
	country = CountryField(_("Country"), blank_label='Country', default='PK')
	zip_code = models.CharField(_("Zip Code"), max_length=12)
	default = models.BooleanField(_("Default"), default=False)

	class Meta:
		verbose_name = 'Billing Address'
		verbose_name_plural = 'Billing Addresses'

	def __str__(self):
		return self.customer.username

address/forms.py
from django import forms

from .models import BillingAddress


class UserAddressForm(forms.ModelForm):
	class Meta:
		model = BillingAddress
		fields = "__all__"
		exclude = ("customer", "default")

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field_name in self.fields:
			self.fields[field_name].widget.attrs.update(
				{
					"class": "form-control mb-2",
					"placeholder": field_name.replace("_", " ").title(),
				}
			)
		self.fields["country"].widget.attrs.update(
			{
				"class": "form-select",
			}
		)
		self.fields["city"].widget.attrs.update(
			{
				"class": "form-select",
			}
		)


class BillingForm(forms.ModelForm):
	first_name = forms.CharField(
		label="First Name",
		min_length=4,
		max_length=50,
		widget=forms.TextInput(
			attrs={
				"class": "form-control",
				"placeholder": "First Name",
			}
		),
	)
	last_name = forms.CharField(
		label="Last Name",
		min_length=4,
		max_length=50,
		widget=forms.TextInput(
			attrs={
				"class": "form-control",
				"placeholder": "Last Name",
			}
		),
	)
	email = forms.EmailField(
		label="Email",
		max_length=200,
		widget=forms.EmailInput(
			attrs={
				"class": "form-control mb-3",
				"placeholder": "email",
			}
		),
	)
	save_info = forms.BooleanField(
		label="Save this information for next time",
		required=False,
		widget=forms.CheckboxInput(),
	)
	PAYMENT_CHOICES = [
		("COD", "Cash on Delivery"),
	]

	payment_method = forms.ChoiceField(
		choices=PAYMENT_CHOICES,
		widget=forms.RadioSelect(
			attrs={
				"checked": "checked",
			}
		), label="Payment Method"
	)

	class Meta:
		model = BillingAddress
		fields = "__all__"
		exclude = ("user",)

		labels = {
			"address_line_1": "Address",
			"address_line_2": "Address 2",
			"state": "State/Province/Region",
		}

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields["phone_number"].widget.attrs.update(
			{
				"class": "form-control",
				"placeholder": "Phone number",
			}
		)
		self.fields["address_line_1"].widget.attrs.update(
			{
				"class": "form-control",
				"placeholder": "Address",
			}
		)
		self.fields["address_line_2"].widget.attrs.update(
			{"class": "form-control", "placeholder": "Address 2"}
		)
		self.fields["city"].widget.attrs.update(
			{"class": "form-select", "placeholder": "City"}
		)
		self.fields["state"].widget.attrs.update(
			{"class": "form-control", "placeholder": "State"}
		)
		self.fields["country"].widget.attrs.update(
			{"class": "form-select", "placeholder": "Country"}
		)
		self.fields["zip_code"].widget.attrs.update(
			{"class": "form-control", "placeholder": "Zip Code"}
		)

address/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import (render, redirect)
from django.db import transaction

from .billingaddress import Billing
from .forms import UserAddressForm
from .models import BillingAddress


@login_required
def address_session_view(request):
	billing_session = Billing(request)
	if request.POST.get('action') == 'post':
		address = BillingAddress.objects.get(customer=request.user, default=True)
		billing_session.addBillingObject(address=address, uid=request.user.id)
	response = JsonResponse('successfully added address', safe=False)
	return response


@login_required
def address_list(request):
	addresses = BillingAddress.objects.filter(customer=request.user)

	return render(request, "address/list.html", {
		'addresses': addresses,
		'checkout': True if 'checkout' in request.META['HTTP_REFERER'] else False
	})


@login_required
def add_address(request):
	"""
    View for adding a new billing address.
    Handles both GET and POST requests with proper validation and error handling.
    """
	template_name = 'address/add.html'
    
    # Check if coming from checkout page
	checkout = request.META.get('HTTP_REFERER', '').find('checkout') != -1

	if request.method != 'POST':
		return render(request, template_name, {
			'form': UserAddressForm(),
			'checkout': checkout
		})

	form = UserAddressForm(request.POST)
	if not form.is_valid():
		return render(request, template_name, {
			'form': form,
			'checkout': checkout
		})

	try:
		with transaction.atomic():
			# Create new address instance but don't save yet
			address = form.save(commit=False)
			address.customer = request.user
			address.default = True
			
			# Bulk update all existing addresses to non-default
			BillingAddress.objects.filter(customer=request.user).update(default=False)
			
			# Save the new address
			address.save()
			
			messages.success(request, 'New Delivery Address has been added')
			return redirect('address:addresses')
			
	except Exception as e:
		messages.error(request, 'Error saving address. Please try again.')
		return render(request, template_name, {
			'form': form,
			'checkout': checkout
		})


@login_required
def edit_address(request, id):
	address = BillingAddress.objects.get(pk=id, customer=request.user)
	if request.POST:
		address_form = UserAddressForm(request.POST, instance=address)
		if address_form.is_valid():
			address_form.save()
			return redirect('address:addresses')
		else:
			return render(request, 'address/add', {
				'form': address_form
			})

	address_form = UserAddressForm(instance=address)
	return render(request, 'address/add.html', {
		'form': address_form
	})


@login_required
def delete_address(request, id):
	try:
		BillingAddress.objects.get(pk=id, customer=request.user).delete()
		messages.success(request, 'Address successfully deleted.')
	except BillingAddress.DoesNotExist:
		messages.error(request, 'Address doesn\'t exist.')
	return redirect('address:addresses')


@login_required
def default_address(request, id):
	try:
		address = BillingAddress.objects.get(pk=id, customer=request.user)
		BillingAddress.objects.filter(customer=request.user).update(default=False)
		address.default = True
		address.save()
	except BillingAddress.DoesNotExist:
		messages.error(request, 'Error: Address doesn\'t exist.')

	return redirect('address:addresses')

templates/address/add.html
{% extends 'store/layout.html' %}
{% load static %}

{% block title %}Sign Up{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/forms.css' %}">
{% endblock style %}

{% block body %}
<div class="container w-100">
	<div class="my-md-4 mb-md-5">
		<div class="row">
			<div class="auth_form col-12 col-lg-8 col-xl-9 mx-auto">
				<form action="" class="rounded mx-auto p-4" method="post">
					{% csrf_token %}
					<h1 class="mb-2">Add Address</h1>
					<p class="mb-4 text-muted">Add a new delivery address</p>

					{% if form.errors %}
					<p class="text-danger">Please correct the following errors:</p>
					{% for field in form %}
					{% if field.errors %}
					<div class="alert alert-danger alert-dismissible fade show" role="alert">
						{{ field.label }}: {{ field.errors | striptags }}
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
					{% endif %}
					{% endfor %}
					{% endif %}

					<div class="row">
						<div class="col-12 col-md-6">
							<label for="id_first_name">{{ form.first_name.label }}</label>
							{{ form.first_name }}
						</div>
						<div class="col-12 col-md-6">
							<label for="id_last_name">{{ form.last_name.label }}</label>
							{{ form.last_name }}
						</div>
					</div>
					<div class="row">
						<div class="col-12 col-md-6">
							<label for="id_email">{{ form.email.label }} <span class="text-muted small">(Optional)</span></label>
							{{ form.email }}
						</div>
						<div class="col-12 col-md-6">
							<label for="id_phone_number">{{ form.phone_number.label }}</label>
							{{ form.phone_number }}
						</div>
					</div>
					<div class="row">
						<div class="col-12 col-md-6">
							<label for="id_address_line_1">{{ form.address_line_1.label }}</label>
							{{ form.address_line_1 }}
						</div>
						<div class="col-12 col-md-6">
							<label for="id_address_line_2">{{ form.address_line_2.label }} <span class="text-muted small">(Optional)</span></label>
							{{ form.address_line_2 }}
						</div>
					</div>
					<div class="row">
						<div class="col-6 col-md">
							<label for="id_city">{{ form.city.label }}</label>
							{{ form.city }}
						</div>
						<div class="col-6 col-md">
							<label for="id_state">{{ form.state.label }}</label>
							{{ form.state }}
						</div>
						<div class="col-6 col-md">
							<label for="id_country">{{ form.country.label }}</label>
							{{ form.country }}
						</div>
						<div class="col-6 col-md">
							<label for="id_zip_code">{{ form.zip_code.label }}</label>
							{{ form.zip_code }}
						</div>
					</div>
					<input class="btn btn-continue" type="submit" value="Save">
					{% if checkout %}
						<a href="{% url 'checkout:checkout' %}" class="btn btn-secondary w-100 d-flex align-items-center justify-content-center gap-2"><ion-icon name="return-down-back-outline"></ion-icon>Back to Checkout</a>
					{% endif %}
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/address/addresses.html
{% extends 'store/layout.html' %}
{% load static %}

{% block title %}Addresses{%endblock %}

{% block style %}
	<link rel="stylesheet" href="{% static 'css/address/card.css' %}" />
{% endblock %}

{% block body %}
<div class="container mb-3">
	<div class="hstack gap-3">
		<!-- <a href="{% url 'store:index' %}" class="link-body-emphasis">
				<img src="{% static 'store/imgs/icon/sanwal2.webp' %}" alt="Logo" width="50" height="45">
			</a> -->
		<!-- <div class="col"> -->
		<h1 class="h5 mb-0">Your Addresses</h1>
		<div class="vr"></div>
		<div class="text-muted">
			Manage your addresses and delivery preferences
		</div>
		<!-- </div> -->
	</div>
	<hr />
	<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
		<div class="col add-address {% if addresses|length == 0 %}mx-auto{% endif %}">
			<div class="card mb-3 h-100 rounded-4 shadow">
				<a
					href="{% url 'address:add_address' %}"
					class="text-reset w-100 h-100"
					role="button"
				>
					<div class="row g-0 h-100">
						<div class="col-12">
							<div
								class="card-body text-center position-absolute top-50 start-50 translate-middle"
							>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									width="60"
									height="60"
									fill="currentColor"
									class="bi bi-plus"
									viewBox="0 0 16 16"
								>
									<path
										d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5"
									></path>
								</svg>
								<h1 class="h5">Add Address</h1>
							</div>
						</div>
					</div>
				</a>
			</div>
		</div>
		{% for address in addresses %}
		<div class="col">
			<div
				class="card h-100 p-3 rounded-4 shadow {% if address.default %}default{% endif %}"
			>
				{% if address.default %}
					<div class="card-header small text-muted text-center">
						Default
					</div>
				{% endif %}
				<div class="card-body small py-2">
					<p class="card-text m-0 fw-bold">
						{{ address.first_name }} {{ address.last_name }}
					</p>
					<p class="card-text m-0">{{ address.phone_number }}</p>
					<p class="card-text m-0">{{ address.email }}</p>
					<p class="card-text m-0">{{ address.address_line_1 }}</p>
					<p class="card-text m-0">{{ address.address_line_2 }}</p>
					<p class="card-text m-0">{{ address.zip_code }}</p>
					<p class="card-text m-0">{{ address.city }}</p>
					<p class="card-text m-0">
						{{ address.get_country_display }}
					</p>
				</div>
				<div class="card-footer text-body-secondary">
					<div class="hstack gap-3 justify-content-center">
						<a href="{% url 'address:edit_address' address.id %}">Edit</a>
						<div class="vr"></div>
						<a href="{% url 'address:delete_address' address.id %}">Delete</a>
	
						{% if not address.default %}
							<div class="vr"></div>
							<a href="{% url 'address:set_default' address.id %}" class="text-decoration-none">Set Default</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/address/list.html
{% extends 'store/layout.html' %}
{% load static %}

{% block title %}Addresses{%endblock %}

{% block style %}
	<link rel="stylesheet" href="{% static 'css/address/card.css' %}" />
{% endblock %}

{% block body %}
<div class="container mt-5 mb-3">
	<div class="hstack gap-3">
		<h1 class="h5 mb-0">Your Addresses</h1>
		<div class="vr"></div>
		<div class="text-muted">
			Manage your addresses and delivery preferences
		</div>
	</div>
	<hr />
	<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mt-3">
		<div class="col add-address {% if addresses|length == 0 %}mx-auto{% endif %}">
			<div class="card mb-3 h-100 rounded-4 shadow">
				<a
					href="{% url 'address:add_address' %}"
					class="text-reset w-100 h-100"
					role="button"
				>
					<div class="row g-0 h-100">
						<div class="col-12">
							<div
								class="card-body text-center position-absolute top-50 start-50 translate-middle"
							>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									width="60"
									height="60"
									fill="currentColor"
									class="bi bi-plus"
									viewBox="0 0 16 16"
								>
									<path
										d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5"
									></path>
								</svg>
								<h1 class="h5">Add Address</h1>
							</div>
						</div>
					</div>
				</a>
			</div>
		</div>
		{% for address in addresses %}
		<div class="col">
			<div
				class="card h-100 p-3 rounded-4 shadow {% if address.default %}default{% endif %}"
			>
				{% if address.default %}
					<div class="card-header small text-muted text-center">
						Default
					</div>
				{% endif %}
				<div class="card-body small py-2">
					<p class="card-text m-0 fw-bold">
						{{ address.first_name }} {{ address.last_name }}
					</p>
					<p class="card-text m-0">{{ address.phone_number }}</p>
					<p class="card-text m-0">{{ address.email }}</p>
					<p class="card-text m-0">{{ address.address_line_1 }}</p>
					<p class="card-text m-0">{{ address.address_line_2 }}</p>
					<p class="card-text m-0">{{ address.zip_code }}</p>
					<p class="card-text m-0">{{ address.city }}</p>
					<p class="card-text m-0">
						{{ address.get_country_display }}
					</p>
				</div>
				<div class="card-footer text-body-secondary">
					<div class="hstack gap-3 justify-content-center">
						<a href="{% url 'address:edit_address' address.id %}">Edit</a>
						<div class="vr"></div>
						<a href="{% url 'address:delete_address' address.id %}">Delete</a>
	
						{% if not address.default %}
							<div class="vr"></div>
							<a href="{% url 'address:set_default' address.id %}" class="text-decoration-none">Set Default</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
	{% if checkout %}
		<a href="{% url 'checkout:checkout' %}" class="btn btn-primary d-flex align-items-center justify-content-center gap-2 w-fit-content ms-auto px-5 mt-5"><ion-icon name="return-down-back-outline"></ion-icon>Back to Checkout</a>
	{% endif %}
</div>
{% endblock %}